# Site settings
title: fabianism.us
email: fabian+github@fabianism.us
description: > # this means to ignore newlines until "baseurl:"
  I am a software engineer living in Raleigh, NC and working in open source on behalf of Red Hat.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fabianism.us" # the base hostname & protocol for your site
twitter_username: fabianismus
github_username:  fabianvf
linkedin_username: fabianvf

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
