# Site settings
title: Musings of Fabian von Feilitzsch
email: fabian+github@fabianism.us
description: > # this means to ignore newlines until "baseurl:"
  I am a software developer living in Charlottesville, VA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fabianism.us" # the base hostname & protocol for your site
twitter_username: fabianismus
github_username:  fabianvf

# Build settings
markdown: kramdown
